!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  Dx: 0.3
  Dy: 0.3
  Dz: 0.3
  Kx: 0.0
  Ky: 0.0
  Kz: 400.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      Dx: 0.3
      Dy: 0.3
      Dz: 0.3
      Kx: 0.0
      Ky: 0.0
      Kz: 400.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      nullspace_damping: 32.0
      nullspace_stiffness: 27.0
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      rotational_damping: 10.0
      rotational_stiffness: 10.0
      state: true
      type: ''
    state: []
  nullspace_damping: 32.0
  nullspace_stiffness: 27.0
  rotational_damping: 10.0
  rotational_stiffness: 10.0
state: []
