!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  Dx: 2.0
  Dy: 2.0
  Dz: 2.0
  Kx: 76.0
  Ky: 76.0
  Kz: 76.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      Dx: 2.0
      Dy: 2.0
      Dz: 2.0
      Kx: 76.0
      Ky: 76.0
      Kz: 76.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      nullspace_damping: 13.0
      nullspace_stiffness: 21.0
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      rotational_damping: 0.3
      rotational_stiffness: 0.3
      state: true
      type: ''
    state: []
  nullspace_damping: 13.0
  nullspace_stiffness: 21.0
  rotational_damping: 0.3
  rotational_stiffness: 0.3
state: []
