rate: 30 

target:
  input_type: 3
  topic_pose: "/virtual_master/master_pose"
  topic_twist: "/virtual_master/master_velocity"

current:
  input_type: 0
  topic_pose: "robot_pose_stamped"
  topic_odom: "odom_enc"

lyapunov: [3.0,4.0,1.0]
topic_output: "cmd_vel"