type: 0        
pause: true
iterations: 1


#Kreis
# omega: 0.05
# ratio: 1
# phaseshift: 4.71238898
# amplifier_x: 0.5
# amplifier_y: 0.5

# Stundenglas
omega: 0.04
ratio: 2
phaseshift: 0
amplifier_x: 3.5
amplifier_y: 2.0

#Ellipse
# omega: 0.05
# ratio: 1
# phaseshift: 5.497787144
# amplifier_x: 0.9
# amplifier_y: 0.5
