type: 0        
pause: true
iterations: 1


#Kreis
# omega: 0.05
# ratio: 1
# phaseshift: 4.71238898
# amplifier_x: 0.5
# amplifier_y: 0.5

# Stundenglas IROS
# omega: 0.04
# ratio: 2
# phaseshift: 0
# amplifier_x: 4
# amplifier_y: 1.75

omega: 0.02
ratio: 2
phaseshift: 0
amplifier_x: 1
amplifier_y: 0.25

#Ellipse
# omega: 0.05
# ratio: 1
# phaseshift: 5.497787144
# amplifier_x: 0.9
# amplifier_y: 0.5
